package entidades;
// Generated 17-ene-2014 16:28:31 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Anuncio generated by hbm2java
 */
public class Anuncio  implements java.io.Serializable {


     private int nro;
     private Subcategoria subcategoria;
     private Vendedor vendedor;
     private Tipoanuncio tipoanuncio;
     private String titulo;
     private String descripcion;
     private float preciobase;
     private Float precioactual;
     private Date fechainicio;
     private Date fechafin;
     private boolean estado;
     private int cantarticulos;
     private Float preciominimo;
     private Set transaccions = new HashSet(0);
     private Set imagens = new HashSet(0);
     private Set enlaces = new HashSet(0);
     private Set pujas = new HashSet(0);
     private Set metododepagos = new HashSet(0);

    public Anuncio() {
    }

	
    public Anuncio(Subcategoria subcategoria, Vendedor vendedor, Tipoanuncio tipoanuncio, String titulo, String descripcion, float preciobase, Date fechainicio, Date fechafin, boolean estado, int cantarticulos) {
        
        this.subcategoria = subcategoria;
        this.vendedor = vendedor;
        this.tipoanuncio = tipoanuncio;
        this.titulo = titulo;
        this.descripcion = descripcion;
        this.preciobase = preciobase;
        this.fechainicio = fechainicio;
        this.fechafin = fechafin;
        this.estado = estado;
        this.cantarticulos = cantarticulos;
    }
    
    public int getNro() {
        return this.nro;
    }
    
    public void setNro(int nro) {
        this.nro = nro;
    }
    public Subcategoria getSubcategoria() {
        return this.subcategoria;
    }
    
    public void setSubcategoria(Subcategoria subcategoria) {
        this.subcategoria = subcategoria;
    }
    public Vendedor getVendedor() {
        return this.vendedor;
    }
    
    public void setVendedor(Vendedor vendedor) {
        this.vendedor = vendedor;
    }
    public Tipoanuncio getTipoanuncio() {
        return this.tipoanuncio;
    }
    
    public void setTipoanuncio(Tipoanuncio tipoanuncio) {
        this.tipoanuncio = tipoanuncio;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public float getPreciobase() {
        return this.preciobase;
    }
    
    public void setPreciobase(float preciobase) {
        this.preciobase = preciobase;
    }
    public Float getPrecioactual() {
        return this.precioactual;
    }
    
    public void setPrecioactual(Float precioactual) {
        this.precioactual = precioactual;
    }
    public Date getFechainicio() {
        return this.fechainicio;
    }
    
    public void setFechainicio(Date fechainicio) {
        this.fechainicio = fechainicio;
    }
    public Date getFechafin() {
        return this.fechafin;
    }
    
    public void setFechafin(Date fechafin) {
        this.fechafin = fechafin;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public int getCantarticulos() {
        return this.cantarticulos;
    }
    
    public void setCantarticulos(int cantarticulos) {
        this.cantarticulos = cantarticulos;
    }
    public Float getPreciominimo() {
        return this.preciominimo;
    }
    
    public void setPreciominimo(Float preciominimo) {
        this.preciominimo = preciominimo;
    }
    public Set getTransaccions() {
        return this.transaccions;
    }
    
    public void setTransaccions(Set transaccions) {
        this.transaccions = transaccions;
    }
    public Set getImagens() {
        return this.imagens;
    }
    
    public void setImagens(Set imagens) {
        this.imagens = imagens;
    }
    public Set getEnlaces() {
        return this.enlaces;
    }
    
    public void setEnlaces(Set enlaces) {
        this.enlaces = enlaces;
    }
    public Set getPujas() {
        return this.pujas;
    }
    
    public void setPujas(Set pujas) {
        this.pujas = pujas;
    }
    public Set getMetododepagos() {
        return this.metododepagos;
    }
    
    public void setMetododepagos(Set metododepagos) {
        this.metododepagos = metododepagos;
    }




}


