package entidades;
// Generated 15-ene-2014 11:08:03 by Hibernate Tools 3.6.0


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Comprador generated by hbm2java
 */
public class Comprador  implements java.io.Serializable {


     private int dni;
     private Localidad localidad;
     private String nombre;
     private String apellido;
     private Serializable email;
     private Date fechanac;
     private String contrasenia;
     private char sexo;
     private int puntuacion;
     private int votos;
     private Boolean estado;
     private Date fecharegistro;
     private String username;
     private Set pujas = new HashSet(0);
     private Set transaccions = new HashSet(0);
     private Vendedor vendedor;

    public Comprador() {
    }

	
    public Comprador(int dni, Localidad localidad, String nombre, String apellido, Serializable email, Date fechanac, String contrasenia, char sexo, int puntuacion, int votos, Date fecharegistro) {
        this.dni = dni;
        this.localidad = localidad;
        this.nombre = nombre;
        this.apellido = apellido;
        this.email = email;
        this.fechanac = fechanac;
        this.contrasenia = contrasenia;
        this.sexo = sexo;
        this.puntuacion = puntuacion;
        this.votos = votos;
        this.fecharegistro = fecharegistro;
    }
    public Comprador(int dni, Localidad localidad, String nombre, String apellido, Serializable email, Date fechanac, String contrasenia, char sexo, int puntuacion, int votos, Boolean estado, Date fecharegistro, String username, Set pujas, Set transaccions, Vendedor vendedor) {
       this.dni = dni;
       this.localidad = localidad;
       this.nombre = nombre;
       this.apellido = apellido;
       this.email = email;
       this.fechanac = fechanac;
       this.contrasenia = contrasenia;
       this.sexo = sexo;
       this.puntuacion = puntuacion;
       this.votos = votos;
       this.estado = estado;
       this.fecharegistro = fecharegistro;
       this.username = username;
       this.pujas = pujas;
       this.transaccions = transaccions;
       this.vendedor = vendedor;
    }
   
    public int getDni() {
        return this.dni;
    }
    
    public void setDni(int dni) {
        this.dni = dni;
    }
    public Localidad getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(Localidad localidad) {
        this.localidad = localidad;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public Serializable getEmail() {
        return this.email;
    }
    
    public void setEmail(Serializable email) {
        this.email = email;
    }
    public Date getFechanac() {
        return this.fechanac;
    }
    
    public void setFechanac(Date fechanac) {
        this.fechanac = fechanac;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    public char getSexo() {
        return this.sexo;
    }
    
    public void setSexo(char sexo) {
        this.sexo = sexo;
    }
    public int getPuntuacion() {
        return this.puntuacion;
    }
    
    public void setPuntuacion(int puntuacion) {
        this.puntuacion = puntuacion;
    }
    public int getVotos() {
        return this.votos;
    }
    
    public void setVotos(int votos) {
        this.votos = votos;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Date getFecharegistro() {
        return this.fecharegistro;
    }
    
    public void setFecharegistro(Date fecharegistro) {
        this.fecharegistro = fecharegistro;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public Set getPujas() {
        return this.pujas;
    }
    
    public void setPujas(Set pujas) {
        this.pujas = pujas;
    }
    public Set getTransaccions() {
        return this.transaccions;
    }
    
    public void setTransaccions(Set transaccions) {
        this.transaccions = transaccions;
    }
    public Vendedor getVendedor() {
        return this.vendedor;
    }
    
    public void setVendedor(Vendedor vendedor) {
        this.vendedor = vendedor;
    }




}


