package entidades;
// Generated 17-ene-2014 16:28:31 by Hibernate Tools 3.6.0



/**
 * Imagen generated by hbm2java
 */
public class Imagen  implements java.io.Serializable {


     private int id;
     private Anuncio anuncio;
     private byte[] archivo;

    public Imagen() {
    }

    public Imagen(Anuncio anuncio, byte[] archivo) {
       this.anuncio = anuncio;
       this.archivo = archivo;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Anuncio getAnuncio() {
        return this.anuncio;
    }
    
    public void setAnuncio(Anuncio anuncio) {
        this.anuncio = anuncio;
    }
    public byte[] getArchivo() {
        return this.archivo;
    }
    
    public void setArchivo(byte[] archivo) {
        this.archivo = archivo;
    }




}


