package entidades;
// Generated 15-ene-2014 11:08:03 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Localidad generated by hbm2java
 */
public class Localidad  implements java.io.Serializable {


     private int cp;
     private Provincia provincia;
     private String nombre;
     private Set compradors = new HashSet(0);

    public Localidad() {
    }

	
    public Localidad(int cp, Provincia provincia, String nombre) {
        this.cp = cp;
        this.provincia = provincia;
        this.nombre = nombre;
    }
    public Localidad(int cp, Provincia provincia, String nombre, Set compradors) {
       this.cp = cp;
       this.provincia = provincia;
       this.nombre = nombre;
       this.compradors = compradors;
    }
   
    public int getCp() {
        return this.cp;
    }
    
    public void setCp(int cp) {
        this.cp = cp;
    }
    public Provincia getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(Provincia provincia) {
        this.provincia = provincia;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getCompradors() {
        return this.compradors;
    }
    
    public void setCompradors(Set compradors) {
        this.compradors = compradors;
    }




}


