package entidades;
// Generated 17-ene-2014 16:28:31 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Metododepago generated by hbm2java
 */
public class Metododepago  implements java.io.Serializable {


     private int cod;
     private String nombre;
     private Set anuncios = new HashSet(0);

    public Metododepago() {
    }

	
    public Metododepago(int cod, String nombre) {
        this.cod = cod;
        this.nombre = nombre;
    }
    public Metododepago(int cod, String nombre, Set anuncios) {
       this.cod = cod;
       this.nombre = nombre;
       this.anuncios = anuncios;
    }
   
    public int getCod() {
        return this.cod;
    }
    
    public void setCod(int cod) {
        this.cod = cod;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getAnuncios() {
        return this.anuncios;
    }
    
    public void setAnuncios(Set anuncios) {
        this.anuncios = anuncios;
    }




}


