package entidades;
// Generated 15-ene-2014 11:08:03 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Pais generated by hbm2java
 */
public class Pais  implements java.io.Serializable {


     private int idpais;
     private String nombre;
     private Set provincias = new HashSet(0);

    public Pais() {
    }

	
    public Pais(int idpais, String nombre) {
        this.idpais = idpais;
        this.nombre = nombre;
    }
    public Pais(int idpais, String nombre, Set provincias) {
       this.idpais = idpais;
       this.nombre = nombre;
       this.provincias = provincias;
    }
   
    public int getIdpais() {
        return this.idpais;
    }
    
    public void setIdpais(int idpais) {
        this.idpais = idpais;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getProvincias() {
        return this.provincias;
    }
    
    public void setProvincias(Set provincias) {
        this.provincias = provincias;
    }




}


