package entidades;
// Generated 15-ene-2014 11:08:03 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Provincia generated by hbm2java
 */
public class Provincia  implements java.io.Serializable {


     private int idprovincia;
     private Pais pais;
     private String nombre;
     private Set localidads = new HashSet(0);

    public Provincia() {
    }

	
    public Provincia(int idprovincia, Pais pais, String nombre) {
        this.idprovincia = idprovincia;
        this.pais = pais;
        this.nombre = nombre;
    }
    public Provincia(int idprovincia, Pais pais, String nombre, Set localidads) {
       this.idprovincia = idprovincia;
       this.pais = pais;
       this.nombre = nombre;
       this.localidads = localidads;
    }
   
    public int getIdprovincia() {
        return this.idprovincia;
    }
    
    public void setIdprovincia(int idprovincia) {
        this.idprovincia = idprovincia;
    }
    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getLocalidads() {
        return this.localidads;
    }
    
    public void setLocalidads(Set localidads) {
        this.localidads = localidads;
    }




}


