package entidades;
// Generated 15-ene-2014 11:08:03 by Hibernate Tools 3.6.0



/**
 * SubcategoriaId generated by hbm2java
 */
public class SubcategoriaId  implements java.io.Serializable {


     private int id;
     private int idcategoria;

    public SubcategoriaId() {
    }

    public SubcategoriaId(int id, int idcategoria) {
       this.id = id;
       this.idcategoria = idcategoria;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getIdcategoria() {
        return this.idcategoria;
    }
    
    public void setIdcategoria(int idcategoria) {
        this.idcategoria = idcategoria;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SubcategoriaId) ) return false;
		 SubcategoriaId castOther = ( SubcategoriaId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getIdcategoria()==castOther.getIdcategoria());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getIdcategoria();
         return result;
   }   


}


