package entidades;
// Generated 17-ene-2014 16:28:31 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Subcategoria generated by hbm2java
 */
public class Subcategoria  implements java.io.Serializable {


     private SubcategoriaId id;
     private Categoria categoria;
     private String nombre;
     private Set anuncios = new HashSet(0);

    public Subcategoria() {
    }

	
    public Subcategoria(SubcategoriaId id, Categoria categoria, String nombre) {
        this.id = id;
        this.categoria = categoria;
        this.nombre = nombre;
    }
    public Subcategoria(SubcategoriaId id, Categoria categoria, String nombre, Set anuncios) {
       this.id = id;
       this.categoria = categoria;
       this.nombre = nombre;
       this.anuncios = anuncios;
    }
   
    public SubcategoriaId getId() {
        return this.id;
    }
    
    public void setId(SubcategoriaId id) {
        this.id = id;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getAnuncios() {
        return this.anuncios;
    }
    
    public void setAnuncios(Set anuncios) {
        this.anuncios = anuncios;
    }




}


