package entidades;
// Generated 15-ene-2014 11:08:03 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Tiposubasta generated by hbm2java
 */
public class Tiposubasta  implements java.io.Serializable {


     private int cod;
     private String nombre;
     private Set subastas = new HashSet(0);

    public Tiposubasta() {
    }

	
    public Tiposubasta(int cod, String nombre) {
        this.cod = cod;
        this.nombre = nombre;
    }
    public Tiposubasta(int cod, String nombre, Set subastas) {
       this.cod = cod;
       this.nombre = nombre;
       this.subastas = subastas;
    }
   
    public int getCod() {
        return this.cod;
    }
    
    public void setCod(int cod) {
        this.cod = cod;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getSubastas() {
        return this.subastas;
    }
    
    public void setSubastas(Set subastas) {
        this.subastas = subastas;
    }




}


