package entidades;
// Generated 17-ene-2014 16:28:31 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Transaccion generated by hbm2java
 */
public class Transaccion  implements java.io.Serializable {


     private float nrotransaccion;
     private Comprador comprador;
     private Anuncio anuncio;
     private String tipo;
     private Float monto;
     private Date fecha;
     private Date hora;

    public Transaccion() {
    }

	
    public Transaccion(float nrotransaccion) {
        this.nrotransaccion = nrotransaccion;
    }
    public Transaccion(float nrotransaccion, Comprador comprador, Anuncio anuncio, String tipo, Float monto, Date fecha, Date hora) {
       this.nrotransaccion = nrotransaccion;
       this.comprador = comprador;
       this.anuncio = anuncio;
       this.tipo = tipo;
       this.monto = monto;
       this.fecha = fecha;
       this.hora = hora;
    }
   
    public float getNrotransaccion() {
        return this.nrotransaccion;
    }
    
    public void setNrotransaccion(float nrotransaccion) {
        this.nrotransaccion = nrotransaccion;
    }
    public Comprador getComprador() {
        return this.comprador;
    }
    
    public void setComprador(Comprador comprador) {
        this.comprador = comprador;
    }
    public Anuncio getAnuncio() {
        return this.anuncio;
    }
    
    public void setAnuncio(Anuncio anuncio) {
        this.anuncio = anuncio;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Float getMonto() {
        return this.monto;
    }
    
    public void setMonto(Float monto) {
        this.monto = monto;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }




}


