package entidades;
// Generated 15-ene-2014 11:08:03 by Hibernate Tools 3.6.0


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Vendedor generated by hbm2java
 */
public class Vendedor  implements java.io.Serializable {


     private int dni;
     private Comprador comprador;
     private Serializable cuil;
     private Boolean estado;
     private Set subastas = new HashSet(0);

    public Vendedor() {
    }

	
    public Vendedor(Comprador comprador, Serializable cuil) {
        this.comprador = comprador;
        this.cuil = cuil;
    }
    public Vendedor(Comprador comprador, Serializable cuil, Boolean estado, Set subastas) {
       this.comprador = comprador;
       this.cuil = cuil;
       this.estado = estado;
       this.subastas = subastas;
    }
   
    public int getDni() {
        return this.dni;
    }
    
    public void setDni(int dni) {
        this.dni = dni;
    }
    public Comprador getComprador() {
        return this.comprador;
    }
    
    public void setComprador(Comprador comprador) {
        this.comprador = comprador;
    }
    public Serializable getCuil() {
        return this.cuil;
    }
    
    public void setCuil(Serializable cuil) {
        this.cuil = cuil;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Set getSubastas() {
        return this.subastas;
    }
    
    public void setSubastas(Set subastas) {
        this.subastas = subastas;
    }




}


